using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blazor.AnimateOnScroll
{
    public record Animation(string Name);

    public static class Animations
    {
        public static Animation Bounce => new Animation("bounce");
        public static Animation Flash => new Animation("flash");
        public static Animation Pulse => new Animation("pulse");
        public static Animation RubberBand => new Animation("rubberBand");
        public static Animation ShakeX => new Animation("shakeX");
        public static Animation ShakeY => new Animation("shakeY");
        public static Animation HeadShake => new Animation("headShake");
        public static Animation Swing => new Animation("swing");
        public static Animation Tada => new Animation("tada");
        public static Animation Wobble => new Animation("wobble");
        public static Animation Jello => new Animation("jello");
        public static Animation BounceIn => new Animation("bounceIn");
        public static Animation BounceInDown => new Animation("bounceInDown");
        public static Animation BounceInLeft => new Animation("bounceInLeft");
        public static Animation BounceInRight => new Animation("bounceInRight");
        public static Animation BounceInUp => new Animation("bounceInUp");
        public static Animation BounceOut => new Animation("bounceOut");
        public static Animation BounceOutDown => new Animation("bounceOutDown");
        public static Animation BounceOutLeft => new Animation("bounceOutLeft");
        public static Animation BounceOutRight => new Animation("bounceOutRight");
        public static Animation BounceOutUp => new Animation("bounceOutUp");
        public static Animation FadeIn => new Animation("fadeIn");
        public static Animation FadeInDown => new Animation("fadeInDown");
        public static Animation FadeInDownBig => new Animation("fadeInDownBig");
        public static Animation FadeInLeft => new Animation("fadeInLeft");
        public static Animation FadeInLeftBig => new Animation("fadeInLeftBig");
        public static Animation FadeInRight => new Animation("fadeInRight");
        public static Animation FadeInRightBig => new Animation("fadeInRightBig");
        public static Animation FadeInUp => new Animation("fadeInUp");
        public static Animation FadeInUpBig => new Animation("fadeInUpBig");
        public static Animation FadeOut => new Animation("fadeOut");
        public static Animation FadeOutDown => new Animation("fadeOutDown");
        public static Animation FadeOutDownBig => new Animation("fadeOutDownBig");
        public static Animation FadeOutLeft => new Animation("fadeOutLeft");
        public static Animation FadeOutLeftBig => new Animation("fadeOutLeftBig");
        public static Animation FadeOutRight => new Animation("fadeOutRight");
        public static Animation FadeOutRightBig => new Animation("fadeOutRightBig");
        public static Animation FadeOutUp => new Animation("fadeOutUp");
        public static Animation FadeOutUpBig => new Animation("fadeOutUpBig");
        public static Animation FlipInX => new Animation("flipInX");
        public static Animation FlipInY => new Animation("flipInY");
        public static Animation FlipOutX => new Animation("flipOutX");
        public static Animation FlipOutY => new Animation("flipOutY");
        public static Animation LightSpeedInRight => new Animation("lightSpeedInRight");
        public static Animation LightSpeedInLeft => new Animation("lightSpeedInLeft");
        public static Animation LightSpeedOutRight => new Animation("lightSpeedOutRight");
        public static Animation LightSpeedOutLeft => new Animation("lightSpeedOutLeft");
        public static Animation RotateIn => new Animation("rotateIn");
        public static Animation RotateInDownLeft => new Animation("rotateInDownLeft");
        public static Animation RotateInDownRight => new Animation("rotateInDownRight");
        public static Animation RotateInUpLeft => new Animation("rotateInUpLeft");
        public static Animation RotateInUpRight => new Animation("rotateInUpRight");
        public static Animation RotateOut => new Animation("rotateOut");
        public static Animation RotateOutDownLeft => new Animation("rotateOutDownLeft");
        public static Animation RotateOutDownRight => new Animation("rotateOutDownRight");
        public static Animation RotateOutUpLeft => new Animation("rotateOutUpLeft");
        public static Animation RotateOutUpRight => new Animation("rotateOutUpRight");
        public static Animation Hinge => new Animation("hinge");
        public static Animation JackInTheBox => new Animation("jackInTheBox");
        private static Animation RollIn => new Animation("rollIn");
        public static Animation RollOut => new Animation("rollOut");
        public static Animation ZoomIn => new Animation("zoomIn");
        public static Animation ZoomInDown => new Animation("zoomInDown");
        public static Animation ZoomInLeft => new Animation("zoomInLeft");
        public static Animation ZoomInRight => new Animation("zoomInRight");
        public static Animation ZoomInUp => new Animation("zoomInUp");
        public static Animation ZoomOut => new Animation("zoomOut");
        public static Animation ZoomOutDown => new Animation("zoomOutDown");
        public static Animation ZoomOutLeft => new Animation("zoomOutLeft");
        public static Animation ZoomOutRight => new Animation("zoomOutRight");
        public static Animation ZoomOutUp => new Animation("zoomOutUp");
        public static Animation SlideInDown => new Animation("slideInDown");
        public static Animation SlideInLeft => new Animation("slideInLeft");
        public static Animation SlideInRight => new Animation("slideInRight");
        public static Animation SlideInUp => new Animation("slideInUp");
        public static Animation SlideOutDown => new Animation("slideOutDown");
        public static Animation SlideOutLeft => new Animation("slideOutLeft");
        public static Animation SlideOutRight => new Animation("slideOutRight");
        public static Animation SlideOutUp => new Animation("slideOutUp");
        public static Animation HeartBeat => new Animation("heartBeat");
        public static Animation FadeInTopLeft => new Animation("fadeInTopLeft");
        public static Animation FadeInTopRight => new Animation("fadeInTopRight");
        public static Animation FadeInBottomLeft => new Animation("fadeInBottomLeft");
        public static Animation FadeInBottomRight => new Animation("fadeInBottomRight");
        public static Animation FadeOutTopLeft => new Animation("fadeOutTopLeft");
        public static Animation FadeOutTopRight => new Animation("fadeOutTopRight");
        public static Animation FadeOutBottomRight => new Animation("fadeOutBottomRight");
        public static Animation FadeOutBottomLeft => new Animation("fadeOutBottomLeft");
        public static Animation BackOutDown => new Animation("backOutDown");
        public static Animation BackOutLeft => new Animation("backOutLeft");
        public static Animation BackOutRight => new Animation("backOutRight");
        public static Animation BackOutUp => new Animation("backOutUp");
    }
}
